t5

diff --git a/.github/workflows/build_master.yml b/.github/workflows/build_master.yml
--- a/.github/workflows/build_master.yml
+++ b/.github/workflows/build_master.yml
@@ -50,7 +50,7 @@ jobs:
 
       # Build the mdBook
       - name: Build mdBook
-        run: MDBOOK_BOOK__LANGUAGE=$BRANCH mdbook build || (cat hacktricks-preprocessor-error.log && exit 1)
+        run: MDBOOK_BOOK__LANGUAGE=$BRANCH mdbook build || (echo "Error logs" && cat hacktricks-preprocessor-error.log && exit 1)
       
       # Cat hacktricks-preprocessor.log
       #- name: Cat hacktricks-preprocessor.log
diff --git a/.github/workflows/translate_sr.yml b/.github/workflows/translate_sr.yml
--- a/.github/workflows/translate_sr.yml
+++ b/.github/workflows/translate_sr.yml
@@ -61,16 +61,9 @@ jobs:
           done
           python scripts/translator.py --language "$LANGUAGE" --branch "$BRANCH" --api-key "$OPENAI_API_KEY" -f "$(cat /tmp/file_paths.txt)" -t 3
 
-      - name: Commit and push changes
-        run: |
-          git checkout $BRANCH
-          git add -A
-          git commit -m "Translated $LANGUAGE files" || true
-          git push --set-upstream origin $BRANCH
-
       - name: Build mdBook
         run: |
-          MDBOOK_BOOK__LANGUAGE=$BRANCH mdbook build || (cat hacktricks-preprocessor-error.log && exit 1)
+          MDBOOK_BOOK__LANGUAGE=$BRANCH mdbook build || (echo "Error logs" && cat hacktricks-preprocessor-error.log && exit 1)
       
       # Login in AWs
       - name: Configure AWS credentials using OIDC
