en

diff --git a/.github/workflows/build_master.yml b/.github/workflows/build_master.yml
--- a/.github/workflows/build_master.yml
+++ b/.github/workflows/build_master.yml
@@ -33,7 +33,7 @@ jobs:
       
       # Build the mdBook
       - name: Build mdBook
-        run: MDBOOK_BOOK__LANGUAGE=$BRANCH mdbook build || (echo "Error logs" && cat hacktricks-preprocessor-error.log && echo "" && echo "" && echo "Debug logs" && (cat hacktricks-preprocessor.log | tail -n 20) && exit 1)
+        run: MDBOOK_BOOK__LANGUAGE=en mdbook build || (echo "Error logs" && cat hacktricks-preprocessor-error.log && echo "" && echo "" && echo "Debug logs" && (cat hacktricks-preprocessor.log | tail -n 20) && exit 1)
       
       # Login in AWs
       - name: Configure AWS credentials using OIDC
